/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Pact {
  export type PactDataStruct = {
    owner: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    ruleType: BigNumberish;
    ruleParams: BytesLike;
    name: string;
    message: string;
    createdAt: BigNumberish;
    releaseRequestedAt: BigNumberish;
    guardianThreshold: BigNumberish;
    guardianApprovalCount: BigNumberish;
    status: BigNumberish;
  };

  export type PactDataStructOutput = [
    owner: string,
    token: string,
    amount: bigint,
    ruleType: bigint,
    ruleParams: string,
    name: string,
    message: string,
    createdAt: bigint,
    releaseRequestedAt: bigint,
    guardianThreshold: bigint,
    guardianApprovalCount: bigint,
    status: bigint
  ] & {
    owner: string;
    token: string;
    amount: bigint;
    ruleType: bigint;
    ruleParams: string;
    name: string;
    message: string;
    createdAt: bigint;
    releaseRequestedAt: bigint;
    guardianThreshold: bigint;
    guardianApprovalCount: bigint;
    status: bigint;
  };
}

export interface PactInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveRelease"
      | "assignGuardians"
      | "calculateCommitmentScore"
      | "cancelPact"
      | "commitmentScore"
      | "createPact"
      | "deposit"
      | "depositERC20"
      | "getGuardians"
      | "getPact"
      | "getUserPacts"
      | "hasGuardianApproved"
      | "pactCount"
      | "release"
      | "requestRelease"
      | "updateGuardians"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommitmentCompleted"
      | "DepositMade"
      | "GuardianApproved"
      | "GuardianAssigned"
      | "PactBroken"
      | "PactCreated"
      | "PactReleased"
      | "ReleaseApproved"
      | "ReleaseRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignGuardians",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCommitmentScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPact",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitmentScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPact",
    values: [AddressLike, BigNumberish, BytesLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardians",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPact",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPacts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasGuardianApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pactCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGuardians",
    values: [BigNumberish, AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCommitmentScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelPact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitmentScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPact", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPact", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserPacts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasGuardianApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pactCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGuardians",
    data: BytesLike
  ): Result;
}

export namespace CommitmentCompletedEvent {
  export type InputTuple = [
    pactId: BigNumberish,
    owner: AddressLike,
    newScore: BigNumberish
  ];
  export type OutputTuple = [pactId: bigint, owner: string, newScore: bigint];
  export interface OutputObject {
    pactId: bigint;
    owner: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositMadeEvent {
  export type InputTuple = [
    pactId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [pactId: bigint, token: string, amount: bigint];
  export interface OutputObject {
    pactId: bigint;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianApprovedEvent {
  export type InputTuple = [pactId: BigNumberish, guardian: AddressLike];
  export type OutputTuple = [pactId: bigint, guardian: string];
  export interface OutputObject {
    pactId: bigint;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianAssignedEvent {
  export type InputTuple = [pactId: BigNumberish, guardian: AddressLike];
  export type OutputTuple = [pactId: bigint, guardian: string];
  export interface OutputObject {
    pactId: bigint;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PactBrokenEvent {
  export type InputTuple = [pactId: BigNumberish];
  export type OutputTuple = [pactId: bigint];
  export interface OutputObject {
    pactId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PactCreatedEvent {
  export type InputTuple = [
    pactId: BigNumberish,
    owner: AddressLike,
    token: AddressLike,
    ruleType: BigNumberish
  ];
  export type OutputTuple = [
    pactId: bigint,
    owner: string,
    token: string,
    ruleType: bigint
  ];
  export interface OutputObject {
    pactId: bigint;
    owner: string;
    token: string;
    ruleType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PactReleasedEvent {
  export type InputTuple = [
    pactId: BigNumberish,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [pactId: bigint, to: string, amount: bigint];
  export interface OutputObject {
    pactId: bigint;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseApprovedEvent {
  export type InputTuple = [pactId: BigNumberish, guardian: AddressLike];
  export type OutputTuple = [pactId: bigint, guardian: string];
  export interface OutputObject {
    pactId: bigint;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseRequestedEvent {
  export type InputTuple = [
    pactId: BigNumberish,
    requester: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    pactId: bigint,
    requester: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    pactId: bigint;
    requester: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Pact extends BaseContract {
  connect(runner?: ContractRunner | null): Pact;
  waitForDeployment(): Promise<this>;

  interface: PactInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveRelease: TypedContractMethod<
    [pactId: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignGuardians: TypedContractMethod<
    [pactId: BigNumberish, guardians: AddressLike[]],
    [void],
    "nonpayable"
  >;

  calculateCommitmentScore: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  cancelPact: TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;

  commitmentScore: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  createPact: TypedContractMethod<
    [
      token: AddressLike,
      ruleType: BigNumberish,
      ruleParams: BytesLike,
      name: string,
      message: string,
      guardianThreshold: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[pactId: BigNumberish], [void], "payable">;

  depositERC20: TypedContractMethod<
    [pactId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getGuardians: TypedContractMethod<[pactId: BigNumberish], [string[]], "view">;

  getPact: TypedContractMethod<
    [pactId: BigNumberish],
    [Pact.PactDataStructOutput],
    "view"
  >;

  getUserPacts: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  hasGuardianApproved: TypedContractMethod<
    [pactId: BigNumberish, guardian: AddressLike],
    [boolean],
    "view"
  >;

  pactCount: TypedContractMethod<[], [bigint], "view">;

  release: TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;

  requestRelease: TypedContractMethod<
    [pactId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateGuardians: TypedContractMethod<
    [pactId: BigNumberish, newGuardians: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveRelease"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignGuardians"
  ): TypedContractMethod<
    [pactId: BigNumberish, guardians: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateCommitmentScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelPact"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitmentScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPact"
  ): TypedContractMethod<
    [
      token: AddressLike,
      ruleType: BigNumberish,
      ruleParams: BytesLike,
      name: string,
      message: string,
      guardianThreshold: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "depositERC20"
  ): TypedContractMethod<
    [pactId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGuardians"
  ): TypedContractMethod<[pactId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPact"
  ): TypedContractMethod<
    [pactId: BigNumberish],
    [Pact.PactDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPacts"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "hasGuardianApproved"
  ): TypedContractMethod<
    [pactId: BigNumberish, guardian: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pactCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRelease"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGuardians"
  ): TypedContractMethod<
    [pactId: BigNumberish, newGuardians: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CommitmentCompleted"
  ): TypedContractEvent<
    CommitmentCompletedEvent.InputTuple,
    CommitmentCompletedEvent.OutputTuple,
    CommitmentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DepositMade"
  ): TypedContractEvent<
    DepositMadeEvent.InputTuple,
    DepositMadeEvent.OutputTuple,
    DepositMadeEvent.OutputObject
  >;
  getEvent(
    key: "GuardianApproved"
  ): TypedContractEvent<
    GuardianApprovedEvent.InputTuple,
    GuardianApprovedEvent.OutputTuple,
    GuardianApprovedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianAssigned"
  ): TypedContractEvent<
    GuardianAssignedEvent.InputTuple,
    GuardianAssignedEvent.OutputTuple,
    GuardianAssignedEvent.OutputObject
  >;
  getEvent(
    key: "PactBroken"
  ): TypedContractEvent<
    PactBrokenEvent.InputTuple,
    PactBrokenEvent.OutputTuple,
    PactBrokenEvent.OutputObject
  >;
  getEvent(
    key: "PactCreated"
  ): TypedContractEvent<
    PactCreatedEvent.InputTuple,
    PactCreatedEvent.OutputTuple,
    PactCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PactReleased"
  ): TypedContractEvent<
    PactReleasedEvent.InputTuple,
    PactReleasedEvent.OutputTuple,
    PactReleasedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseApproved"
  ): TypedContractEvent<
    ReleaseApprovedEvent.InputTuple,
    ReleaseApprovedEvent.OutputTuple,
    ReleaseApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseRequested"
  ): TypedContractEvent<
    ReleaseRequestedEvent.InputTuple,
    ReleaseRequestedEvent.OutputTuple,
    ReleaseRequestedEvent.OutputObject
  >;

  filters: {
    "CommitmentCompleted(uint256,address,uint256)": TypedContractEvent<
      CommitmentCompletedEvent.InputTuple,
      CommitmentCompletedEvent.OutputTuple,
      CommitmentCompletedEvent.OutputObject
    >;
    CommitmentCompleted: TypedContractEvent<
      CommitmentCompletedEvent.InputTuple,
      CommitmentCompletedEvent.OutputTuple,
      CommitmentCompletedEvent.OutputObject
    >;

    "DepositMade(uint256,address,uint256)": TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;
    DepositMade: TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;

    "GuardianApproved(uint256,address)": TypedContractEvent<
      GuardianApprovedEvent.InputTuple,
      GuardianApprovedEvent.OutputTuple,
      GuardianApprovedEvent.OutputObject
    >;
    GuardianApproved: TypedContractEvent<
      GuardianApprovedEvent.InputTuple,
      GuardianApprovedEvent.OutputTuple,
      GuardianApprovedEvent.OutputObject
    >;

    "GuardianAssigned(uint256,address)": TypedContractEvent<
      GuardianAssignedEvent.InputTuple,
      GuardianAssignedEvent.OutputTuple,
      GuardianAssignedEvent.OutputObject
    >;
    GuardianAssigned: TypedContractEvent<
      GuardianAssignedEvent.InputTuple,
      GuardianAssignedEvent.OutputTuple,
      GuardianAssignedEvent.OutputObject
    >;

    "PactBroken(uint256)": TypedContractEvent<
      PactBrokenEvent.InputTuple,
      PactBrokenEvent.OutputTuple,
      PactBrokenEvent.OutputObject
    >;
    PactBroken: TypedContractEvent<
      PactBrokenEvent.InputTuple,
      PactBrokenEvent.OutputTuple,
      PactBrokenEvent.OutputObject
    >;

    "PactCreated(uint256,address,address,uint8)": TypedContractEvent<
      PactCreatedEvent.InputTuple,
      PactCreatedEvent.OutputTuple,
      PactCreatedEvent.OutputObject
    >;
    PactCreated: TypedContractEvent<
      PactCreatedEvent.InputTuple,
      PactCreatedEvent.OutputTuple,
      PactCreatedEvent.OutputObject
    >;

    "PactReleased(uint256,address,uint256)": TypedContractEvent<
      PactReleasedEvent.InputTuple,
      PactReleasedEvent.OutputTuple,
      PactReleasedEvent.OutputObject
    >;
    PactReleased: TypedContractEvent<
      PactReleasedEvent.InputTuple,
      PactReleasedEvent.OutputTuple,
      PactReleasedEvent.OutputObject
    >;

    "ReleaseApproved(uint256,address)": TypedContractEvent<
      ReleaseApprovedEvent.InputTuple,
      ReleaseApprovedEvent.OutputTuple,
      ReleaseApprovedEvent.OutputObject
    >;
    ReleaseApproved: TypedContractEvent<
      ReleaseApprovedEvent.InputTuple,
      ReleaseApprovedEvent.OutputTuple,
      ReleaseApprovedEvent.OutputObject
    >;

    "ReleaseRequested(uint256,address,uint256)": TypedContractEvent<
      ReleaseRequestedEvent.InputTuple,
      ReleaseRequestedEvent.OutputTuple,
      ReleaseRequestedEvent.OutputObject
    >;
    ReleaseRequested: TypedContractEvent<
      ReleaseRequestedEvent.InputTuple,
      ReleaseRequestedEvent.OutputTuple,
      ReleaseRequestedEvent.OutputObject
    >;
  };
}
