/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PactInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createPact"
      | "deposit"
      | "pactCount"
      | "pacts"
      | "release"
      | "requestRelease"
      | "userPacts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DepositMade" | "PactCreated" | "PactReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createPact",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pactCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "pacts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userPacts",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createPact", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pactCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pacts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userPacts", data: BytesLike): Result;
}

export namespace DepositMadeEvent {
  export type InputTuple = [pactId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [pactId: bigint, amount: bigint];
  export interface OutputObject {
    pactId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PactCreatedEvent {
  export type InputTuple = [
    pactId: BigNumberish,
    owner: AddressLike,
    amount: BigNumberish,
    lockedUntil: BigNumberish
  ];
  export type OutputTuple = [
    pactId: bigint,
    owner: string,
    amount: bigint,
    lockedUntil: bigint
  ];
  export interface OutputObject {
    pactId: bigint;
    owner: string;
    amount: bigint;
    lockedUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PactReleasedEvent {
  export type InputTuple = [pactId: BigNumberish, to: AddressLike];
  export type OutputTuple = [pactId: bigint, to: string];
  export interface OutputObject {
    pactId: bigint;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Pact extends BaseContract {
  connect(runner?: ContractRunner | null): Pact;
  waitForDeployment(): Promise<this>;

  interface: PactInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createPact: TypedContractMethod<
    [_lockedUntil: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[pactId: BigNumberish], [void], "payable">;

  pactCount: TypedContractMethod<[], [bigint], "view">;

  pacts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        owner: string;
        amount: bigint;
        lockedUntil: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;

  release: TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;

  requestRelease: TypedContractMethod<
    [pactId: BigNumberish],
    [void],
    "nonpayable"
  >;

  userPacts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createPact"
  ): TypedContractMethod<[_lockedUntil: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "pactCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pacts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        owner: string;
        amount: bigint;
        lockedUntil: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRelease"
  ): TypedContractMethod<[pactId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPacts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "DepositMade"
  ): TypedContractEvent<
    DepositMadeEvent.InputTuple,
    DepositMadeEvent.OutputTuple,
    DepositMadeEvent.OutputObject
  >;
  getEvent(
    key: "PactCreated"
  ): TypedContractEvent<
    PactCreatedEvent.InputTuple,
    PactCreatedEvent.OutputTuple,
    PactCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PactReleased"
  ): TypedContractEvent<
    PactReleasedEvent.InputTuple,
    PactReleasedEvent.OutputTuple,
    PactReleasedEvent.OutputObject
  >;

  filters: {
    "DepositMade(uint256,uint256)": TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;
    DepositMade: TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;

    "PactCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      PactCreatedEvent.InputTuple,
      PactCreatedEvent.OutputTuple,
      PactCreatedEvent.OutputObject
    >;
    PactCreated: TypedContractEvent<
      PactCreatedEvent.InputTuple,
      PactCreatedEvent.OutputTuple,
      PactCreatedEvent.OutputObject
    >;

    "PactReleased(uint256,address)": TypedContractEvent<
      PactReleasedEvent.InputTuple,
      PactReleasedEvent.OutputTuple,
      PactReleasedEvent.OutputObject
    >;
    PactReleased: TypedContractEvent<
      PactReleasedEvent.InputTuple,
      PactReleasedEvent.OutputTuple,
      PactReleasedEvent.OutputObject
    >;
  };
}
